global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "starpu-inference-server"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          instance: "local"

rule_files:
  - alerts.yml
